### ISSUE TITLE
Bugs....

### ISSUE THREAD

**Issue by Deathlymad** [Forte40/bee#3]
Hey there, 
1st thing: AMAZING this program is genius. I hope you will keep porting it.
2nd bug:
if you enter what species you want to breed. it just says in the next line: "I am going to breed:"(the name is missing)
3rd suggestion: You should check the chest below for more optimal drones. This would be useful if the program accidently breeds back.

**Comment by Zixxl** [comment]
Regarding the bug, did you enter the correct name? (case sensitive)

**Comment by Deathlymad** [comment]
I think so...

**Comment by Forte40** [comment]
Checking the chest would be difficult in this version.  Without OpenPeripherals, you can only pull what's at the top left.  I'd have to setup a second chest to dump everything to as I pull all the bees, then move then all back.  I'm going to be working on a second version that will use OpenPeripherals that will incorporate this type of functionality.  So, closed for now.

I think you probably did type the name wrong.  Case matters.  If it's still an issue, open a second bug report.
